server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILE:develop}

---

spring:
  profiles: develop
  main:
    banner-mode: 'off'
  datasource:
    enabled: false
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABSAE_HOST:localhost}:${DATABASE_PORT:5432}/${$DATABASE_NAME:database}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    user:
      name: edr
      password: edr
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

---

spring:
  profiles: production
  main:
    banner-mode: 'off'
  datasource:
    enabled: false
    driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DATABSAE_HOST:localhost}:${DATABASE_PORT:5432}/${$DATABASE_NAME:database}
      username: ${DATABASE_USERNAME:postgres}
      password: ${DATABASE_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    user:
      name: edr
      password: edr
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
