server:
  port: 8080
spring:
  profiles: develop
  main:
    banner-mode: 'off'
  datasource:
    enabled: false
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/edr-develop
    username: edr
    password: edr
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    user:
      name: edr
      password: edr
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

---
server:
  port: 10001

spring:
  profiles: production
  main:
    banner-mode: 'off'
  datasource:
    enabled: false
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/edr-production
    username: edr
    password: edr
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  security:
    user:
      name: edr
      password: edr
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
